name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Egy soros script
        run: echo Helló világ!
      - name: Töb soros script
        run: |
          echo "További sorok"
          echo "Bármilyen parancsot is futtathatnánk"
